### ISSUE TITLE
애니메이션 디자인 참고안.

### ISSUE THREAD

**Issue by CodeName393** [anissia-net/anissia-web-2022#1]
따로 가이드라인은 모르기 때문에 사이트 내에 색상값, padding, 라운드 등등을 참고했습니다.
전에 기능 요청한 일본어 원제 삽입도 포함했습니다.
또한, 웹사이트도 홈페이지 뿐만이 아닌 트위터 같은 애니메이션 공식 트위터 링크도 달수 있도록 하였스면 좋겠습니다.
![화면 캡처 2022-10-21 153923](https://user-images.githubusercontent.com/62503817/197129550-2e2a76e7-b7ab-4b47-90ab-6868a779a99b.png)

**Comment by marker-seoul** [comment]
1. 저 화면이 https://anissia.net/anime 화면이라고 보면 되나요.
2. 추가 되어야 하는 것이 "원제", "트위터" 이렇게 2가지 맞는지 확인해주세요.
기능 추가는 확정되면 https://github.com/anissia-net/anissia-core/issues 여기로 옮기겠습니다.

FE 디자인 프로젝트: https://github.com/anissia-net/anissia-web-2022
BE 시스템 프로젝트: https://github.com/anissia-net/anissia-core

**Comment by CodeName393** [comment]
> 1. 저 화면이 https://anissia.net/anime 화면이라고 보면 되나요.
> 2. 추가 되어야 하는 것이 "원제", "트위터" 이렇게 2가지 맞는지 확인해주세요.
>    기능 추가는 확정되면 https://github.com/anissia-net/anissia-core/issues 여기로 옮기겠습니다.
> 
> FE 디자인 프로젝트: https://github.com/anissia-net/anissia-web-2022 BE 시스템 프로젝트: https://github.com/anissia-net/anissia-core

1. 네, Anime 부분입니다. 제가 디자인한건 참고용으로만 봐주시면 될 거 같습니다!
2. 기능 추가는 원제, 트위터 링크 이 2가지 맞습니다. 링크는 디자인한대로 버튼식으로 해주시면 좋을거같습니다!

**Comment by marker-seoul** [comment]
기능문제는 아래 2개로 분류해서 다시 만들었습니다.
- https://github.com/anissia-net/anissia-core/issues/16
- https://github.com/anissia-net/anissia-core/issues/15

**Comment by marker-seoul** [comment]
이 이슈는 해결되어 종료하겠습니다.
