### ISSUE TITLE
애니메이션 페이지 오류 제보

### ISSUE THREAD

**Issue by CodeName393** [anissia-net/anissia-web-2022#2]
오류 증상 영상 : https://linksharing.samsungcloud.com/cRsX1Dh34rEN

다른 페이지로 이동 후 다시 애니메이션 페이지로 올 시 오류가 발생합니다.

**Comment by marker-seoul** [comment]
저는 이 증상이 재현 되지 않습니다.
혹시 pc에서도 증상이 재현 되나요.
아니면 재현한 기기와 브라우저 이름을 알 수 있을까요.
또 기기(안드로이드/아이폰) 내 다른 브라우저에서도 재현 가능한지 문의 드립니다.

저는 다음과같이 테스트 했습니다.
유형 1
1. 애니메이션으로 이동.
2. 리스트 중 하나 클릭.
3. 뒤로가기
4. 리스트중 하나 클릭. (정상)

유형 2
1. 애니메이션으로 이동.
2. 리스트 중 하나 클릭.
3. 애니메이션으로 이동. (뒤로가기 아님)
4. 리스트중 하나 클릭. (정상)

**Comment by CodeName393** [comment]
> 저는 이 증상이 재현 되지 않습니다. 혹시 pc에서도 증상이 재현 되나요. 아니면 재현한 기기와 브라우저 이름을 알 수 있을까요. 또 기기(안드로이드/아이폰) 내 다른 브라우저에서도 재현 가능한지 문의 드립니다.
> 
> 저는 다음과같이 테스트 했습니다. 유형 1
> 
> 1. 애니메이션으로 이동.
> 2. 리스트 중 하나 클릭.
> 3. 뒤로가기
> 4. 리스트중 하나 클릭. (정상)
> 
> 유형 2
> 
> 1. 애니메이션으로 이동.
> 2. 리스트 중 하나 클릭.
> 3. 애니메이션으로 이동. (뒤로가기 아님)
> 4. 리스트중 하나 클릭. (정상)

현재 다시 시도해보니 증상은 재현되지 않습니다.

버그 발생 재현 방법은
1. 최신 애니메이션 정보를 띄어놓는다
2. 윗 메뉴를 통해 다른 페이지를 이동
3. 뒤로 가기 후 애니메이션 목록으로 이동
4. 버그 발생

추후 버그가 다시 발생하면 다시 이슈 열도록 하겠습니다.

**Comment by marker-seoul** [comment]
아.. 아마 그렇다면 새벽에 제가 서버를 자주 끄거나 재 시작 해서 그럴 수 있습니다. ..
