### ISSUE TITLE
화면 폭이 좁을 경우 테이블 부분이 웹 표시 부분을 넘어가버림

### ISSUE THREAD

**Issue by CodeName393** [anissia-net/anissia-web-2022#3]
![Screenshot_20221101_013606_Samsung Internet](https://user-images.githubusercontent.com/62503817/199060887-b03ae545-9835-470e-a5e5-497c2c442d8c.png)

**Comment by marker-seoul** [comment]
줄바꿈 옵션을 넣어 수정하였습니다.

다만 너무 좁아지면 어쩔 수 없이 증상이 생깁니다. 
(UI자체를 표시할 공간보다 줄어들 경우.)
